database:
  userManagement:
    host: localhost
    port: 5306
    username: root
    password: root
    dbname: user_services
  eMoney:
    host: localhost
    port: 5306
    username: root
    password: root
    dbname: e_money_services